name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Docker
        run: |
          docker build -t app-deploy-demo .
          docker run -d -p 8080:8080 app-deploy-demo
